spring.datasource.url=jdbc:postgresql://localhost:5432/smile_tool
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


com.daypaytechnologies.cloudapp.server-url=http://localhost:8080